stages:
  - lint
  - test
  - build
  - deploy

variables:
  PUBLIC_URL: "/book-shelf"

lint:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npm run lint

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm test

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/


pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp build/index.html public/
  artifacts:
    paths:
      - public
  pages: true